# Generated by Django 3.1.6 on 2021-02-07 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_link', models.CharField(blank=True, max_length=300, null=True)),
                ('git_link', models.CharField(blank=True, max_length=300, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=300, null=True)),
                ('instragram_link', models.CharField(blank=True, max_length=300, null=True)),
                ('fb_link', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
