# Generated by Django 3.1.6 on 2021-03-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0009_auto_20210303_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
